### ISSUE TITLE
Springer styles - new list

### ISSUE THREAD

**Issue by zuphilip** [citation-style-language/utilities#17]
<b>Good news</b>: I received last week an updated list from springer about their citation and reference styles. These are information for almost 2.200 journals. I would like to work on that list a little and add the shortTitle as well as the primary language from the other large Springer list (this is connected to https://github.com/citation-style-language/styles/issues/1122). This would enable us to update the Springer journals and give language support (overwrite local). @rmzelle There are also some Dutch journals in the list, e.g. <a href="http://link.springer.com/journal/12451">"Jeugdbeleid"</a> (no idea what this word means;). This may take some time until I can do that.

(BTW if you will ever ask Springer about this list, they will say that they do not have such a list, which is partially true, because the list has to be generated from the database [I have the exact query].)

**Comment by rmzelle** [comment]
Great, thanks! ("jeugdbeleid" is "youth policies")

**Comment by rmzelle** [comment]
Any news on this? Let me know if you need help.

**Comment by zuphilip** [comment]
I worked a little in Excel on the list and combined the data with other tables to obtain one main table with all information (I can send you that if you want). I certainly would need much longer for everything in Ruby and I don't have your experience with the creation of dependent styles. Would you like to take it over from here?

**Comment by rmzelle** [comment]
Once you have Ruby set up, using the script itself should be rather straightforward. It has an option to replace all dependent styles generated from the "springer" data subdirectory with newly generated styles (`ruby generate_styles_from_data.rb --dir springer --replace`).

But I can do that as well. Can you share the spreadsheet via email or Google Drive?
