### ISSUE TITLE
Recast csl-reindenting-and-info-reordering.py in JavaScript

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/utilities#18]
We often ask style contributors to reindent their CSL styles, but there aren't really any user friendly tools available for this online. In addition, @fbennett has been busy working on a CSL(-m) style validator/editor (http://juris-m.github.io/), and we have of course http://validator.citationstyles.org/.

It would be real handy if the validator/editor could automatically reindent the XML and apply the same reformatting as currently encoded in csl-reindenting-and-info-reordering.py (which includes some character escaping and element reordering). Recasting this Python script in JavaScript would make it much easier to integrate in a webtool.

For indentation, https://github.com/vkiryukhin/vkBeautify seems like a nice JS library. I'm not sure about the best way to make other types of modifications to the XML. I found http://nbubna.github.io/HTML/, but we might also be able to just use the browser's DOMParser and XPath (https://developer.mozilla.org/en-US/docs/Web/Guide/Parsing_and_serializing_XML).

Ideally we would match the output of csl-reindenting-and-info-reordering.py 100%.

**Comment by fbennett** [comment]
This can definitely happen. I need a similar reformatting facility for the modular legal styles that the Juris-M site supports.

**Comment by rmzelle** [comment]
Done in https://github.com/rmzelle/style-formatter
