### ISSUE TITLE
Migration to https://github.com/citation-style-language/journals

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/utilities#38]
I just created a new repository, [journals](https://github.com/citation-style-language/journals), to hold the journal metadata originally maintained in "utilities/generate_dependent_styles", and migrated the files and their git history using "git subtree split", as documented at https://makingsoftware.wordpress.com/2013/02/16/using-git-subtrees-for-repository-separation/.

@adam3smith, @zuphilip, please don't commit or make PRs to "utilities/generate_dependent_styles" anymore. Once I correct the style generation script in "journals" to deal with the new directory structure, and confirm everything works, I plan to delete "utilities/generate_dependent_styles" to complete the migration.

**Comment by adam3smith** [comment]
OK, thanks
